name: exchange_frontend
description: "A new Flutter project."

publish_to: 'none' 

version: 0.0.0+1

environment:
  sdk: ^3.3.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  country_picker: ^2.0.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - build/assets/images/